version:  '3'

networks:
  default:
    external:
      name: ${EXTERNAL_NET}

services:
  web:
    restart: on-failure
    environment:
      XDEBUG_CONFIG:  remote_host=${IP_LISTEN_XDEBUG}
      PHP_IDE_CONFIG: serverName=${APP}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
        USER: ${USER}
        USER_NAME: ${USER_NAME}
        USER_EMAIL: ${USER_EMAIL}
        USER_ID: ${USER_ID}
    volumes:
      - './app/:/var/www/app'
      - './app/var/log:/var/www/app/var/log'

  nginx:
    container_name: ${APP}
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './app/public/:/var/www/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './docker/nginx/logs:/var/log/nginx'
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - web
